title: "Adam Nijhawan"
url: "https://adamnijhawan.github.io"
baseurl: ""                 # keep empty for a user site
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/


thesis:
  title: "Modeling Dynamics and Conformational Ensembles of Biological Macromolecules with Time-Resolved X-ray Scattering and MOlecular Simulations"
  year: 2025
  url: "https://www.proquest.com/openview/3bb871c701216cde5ef30101d279b6fe/1?cbl=18750&diss=y&pq-origsite=gscholar"
  # pdf: "/thesis.pdf"
